# Generated by Django 3.2 on 2021-12-10 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permiso', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='phno',
            field=models.BigIntegerField(default=9347804746),
        ),
        migrations.AlterField(
            model_name='lecturer',
            name='phno',
            field=models.BigIntegerField(default=9347804746),
        ),
    ]
