# Generated by Django 3.2 on 2021-12-10 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permiso', '0002_auto_20211210_1207'),
    ]

    operations = [
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stu', models.CharField(max_length=100)),
                ('subject', models.CharField(max_length=100)),
                ('req', models.TextField()),
                ('img', models.ImageField(upload_to='pics')),
                ('grant', models.CharField(default='Grant', max_length=100)),
            ],
        ),
    ]
