# Generated by Django 3.2 on 2021-12-11 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permiso', '0003_permission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permission',
            name='grant',
            field=models.CharField(default='Not seen', max_length=100),
        ),
    ]
